# Generated by Django 5.2.11 on 2026-02-21 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instagram', '0002_alter_post_media_url_alter_post_permalink'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='media_url',
            field=models.URLField(max_length=700),
        ),
        migrations.AlterField(
            model_name='post',
            name='permalink',
            field=models.URLField(max_length=700),
        ),
    ]
